---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: install required packages
      pacman:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    - name: install required packages for laptop
      pacman:
        name: "{{ packages }}"
        state: present
      when: laptop is defined and laptop
      tags:
        - packages

    - name: setup ufw
      ufw:
        policy: "{{ item.state }}"
        direction: "{{ item.direction }}"
      loop:
        - { state: "allow", direction: "outgoing" }
        - { state: "deny", direction: "incoming" }
        - { state: "deny", direction: "routed" }
      notify: reload ufw
      when: ansible_virtualization_type != "docker"
      tags:
        - network

    - name: setup hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
      tags:
        - network

    - name: setup hostname
      lineinfile:
        path: /etc/hostname
        line: "{{ hostname }}"
      tags:
        - network

    - name: setup resolv.conf file
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
      tags:
        - network

    - name: configure dhcpcd to not assign ipv6 addresses
      lineinfile:
        path: /etc/dhcpcd.conf
        line: "{{ item }}"
      loop:
        - "noipv6rs"
        - "noipv6"
      tags:
        - network

    - name: setup mirrorlist.conf
      template:
        src: mirrorlist.conf.j2
        dest: /etc/pacman.d/mirrorlist
        owner: root
        group: root
        mode: 0644
      tags:
        - network

    - name: setup time
      file:
        state: link
        force: yes
        src: "/usr/share/zoneinfo/{{ timezone }}"
        dest: /etc/localtime
        owner: root
        group: root
        mode: 0644
      tags:
        - locale

    - name: setup locale.conf
      template:
        src: locale.conf.j2
        dest: /etc/locale.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - run locale-gen
      tags:
        - locale

    - name: setup locale.gen
      template:
        src: locale.gen.j2
        dest: /etc/locale.gen
        owner: root
        group: root
        mode: 0644
      notify:
        - run locale-gen
      tags:
        - locale

    - name: setup fontconfig
      template:
        src: fontconfig.j2
        dest: /etc/fonts/conf.avail/99-final.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - run fc-cache
      tags:
        - fonts

    - name: setup fontconfig symlinks
      file:
        state: link
        force: yes
        src: "/etc/fonts/conf.avail/{{ item }}"
        dest: "/etc/fonts/conf.d/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:
        "{{ fontconfig_symlinks }}"
      notify:
        - run fc-cache
      tags:
        - fonts

    - name: setup freetype
      template:
        src: freetype2.sh.j2
        dest: /etc/profile.d/freetype2.sh
        owner: root
        group: root
        mode: 0644
      notify:
        - run fc-cache
      when: freetype_mode != "auto"
      tags:
        - fonts

    - name: setup font and theme and perform few other tweaks on gnome shell
      become: yes
      become_user: "{{ user }}"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { key: '/org/gnome/desktop/applications/terminal/exec', value: "'tilix'" }
        - { key: '/org/gnome/desktop/applications/terminal/exec-arg', value: "'--geometry 120x40'" }
        - { key: '/org/gnome/desktop/interface/clock-show-seconds', value: "true" }
        - { key: '/org/gnome/desktop/interface/clock-show-weekday', value: "true" }
        - { key: '/org/gnome/desktop/interface/document-font-name', value: "'{{ sans_font }} {{ font_size }}'" }
        - { key: '/org/gnome/desktop/interface/font-name', value: "'{{ sans_font }} {{ font_size }}'" }
        - { key: '/org/gnome/desktop/interface/gtk-theme', value: "'{{ gtk_theme }}'" }
        - { key: '/org/gnome/desktop/interface/icon-theme', value: "'{{ icon_theme }}'" }
        - { key: '/org/gnome/desktop/interface/monospace-font-name', value: "'{{ monospace_font }} {{ font_size }}'" }
        - { key: '/org/gnome/desktop/notifications/show-in-lock-screen', value: "false" }
        - { key: '/org/gnome/desktop/privacy/disable-camera', value: 'false' }
        - { key: '/org/gnome/desktop/privacy/disable-microphone' , value: 'false' }
        - { key: '/org/gnome/desktop/privacy/remove-old-temp-files' , value: 'true' }
        - { key: '/org/gnome/desktop/search-providers/disable-external', value: "false" }
        - { key: '/org/gnome/desktop/sound/event-sounds', value: "false" }
        - { key: '/org/gnome/desktop/wm/preferences/audible-bell', value: 'false' }
        - { key: '/org/gnome/desktop/wm/preferences/button-layout', value: "'appmenu:minimize,maximize,close'" }
        - { key: '/org/gnome/desktop/wm/preferences/titlebar-font', value: "'{{ sans_font }} {{ font_size }}'" }
        - { key: '/org/gnome/mutter/center-new-windows', value: "true" }
        - { key: '/org/gnome/settings-daemon/plugins/xsettings/antialiasing', value: "'rgba'" }
        - { key: '/org/gnome/settings-daemon/plugins/xsettings/hinting', value: "'slight'" }
        - { key: '/org/gnome/settings-daemon/plugins/xsettings/rgba-order', value: "'rgb'" }
        - { key: '/org/gnome/shell/disable-user-extensions', value: "true" }
      tags:
        - gnome
        - fonts

    - name: remove desktop icons
      file:
        path: "{{ item }}"
        state: absent
      loop:
        "{{ absent_desktop_icons }}"
      tags:
        - gnome

    - name: ensure critical services are running
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        "{{ critical_services }}"
      tags:
        - services

    - name: ensure critical services are running on laptop
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      when: laptop is defined and laptop
      loop:
        "{{ critical_laptop_services }}"
      tags:
        - services

    - name: enable tlp-sleep service
      systemd:
        name: tlp-sleep.service
        enabled: yes
      when: laptop is defined and laptop
      tags:
        - services

    - name: mask some user services
      become: yes
      become_user: "{{ user }}"
      systemd:
        name: "{{ item }}"
        scope: user
        masked: yes
      loop:
        "{{ masked_user_services }}"
      tags:
        - services

    - name: mask some system services
      systemd:
        name: "{{ item }}"
        masked: yes
        enabled: no
        state: stopped
      loop:
        "{{ masked_system_services }}"
      tags:
        - services

    - name: setup environment variables
      lineinfile:
        line: "{{ item }}"
        path: /etc/environment
      loop:
        "{{ environment_vars }}"
      tags:
        - environment

    - name: make user part of important groups
      user:
        name: "{{ user }}"
        group: "{{ user }}"
        groups: ["audio", "video", "storage", "optical", "wheel"]
      tags:
        - user

    - name: prepare vim plug directories
      become: yes
      become_user: "{{ user }}"
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - /home/{{ user }}/.vim/autoload
        - /home/{{ user }}/.vim/plugged
      tags:
        - vim

    - name: install vim-plug
      become: yes
      become_user: "{{ user }}"
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ item  }}"
        owner: "{{ user }}"
        group: "{{ user }}"
      when: not ansible_check_mode
      loop:
        - /home/{{ user }}/.vim/autoload/plug.vim
      tags:
        - vim

    - name: put plugins into plugged directory
      become: yes
      become_user: "{{ user }}"
      git:
        repo: "{{ item }}"
        dest: "/home/{{ user }}/.vim/plugged/{{ item.split('/')[4] }}"
        update: yes
        force: yes
        depth: 1
      when: vim_plugins is defined and not ansible_check_mode
      loop: "{{ vim_plugins }}"
      tags:
        - vim

    - name: provision .vimrc
      template:
        src: vimrc.j2
        dest: "{{ item }}"
        owner: "{{ user }}"
        group: "{{ user }}"
      loop:
        - "/home/{{ user }}/.vimrc"
        - "/root/.vimrc"
      tags:
        - vim

    - name: provision .gitconfig
      template:
        src: gitconfig.j2
        dest: "/home/{{ user }}/.gitconfig"
        owner: "{{ user }}"
        group: "{{ user }}"
      tags:
        - git

  handlers:
    - name: run locale-gen
      command: locale-gen

    - name: run fc-cache
      command: fc-cache -r

    - name: reload ufw
      command: ufw reload
